services:
  build:
    environment:
      HOSTUID: ${HOSTUID}
      HOSTGID: ${HOSTGID}
      VERSION: ${VERSION}
      WORKSPACE: ${WORKSPACE}
    image: andy5995/linuxdeploy:v2-focal
    platform: "${PLATFORM:-linux/amd64}"
    entrypoint: "${ENTRYPOINT:-/entrypoint.sh}"
    volumes:
      - $PWD:$WORKSPACE
    working_dir: $WORKSPACE

    # Note that SCRIPT is not used by the container, therefore
    # is not included within the 'environment' section above
    #
    # Absolute path or Relative to workspace
    # e.g. $WORKSPACE/path/to/script
    command: "${SCRIPT:-mk/linux/build-appimage.sh}"
